const msg = [
  "BOT QUICK GUIDE",
  "",
  "SESSIONS AND PROJECTS",
  "/new - new session",
  "/sessions - session list, tap = resume",
  "/messages - message history (revert/fork)",
  "/rename - rename session",
  "/projects - switch folder/project",
  "/open - add a new project folder",
  "/worktree - switch git worktree",
  "/status - where am I, which model",
  "/abort - interrupt the current task",
  "",
  "WORK",
  "Plain text = a prompt to opencode.",
  "Code comes back as files to download.",
  "Queue: messages sent while the agent works wait in a queue.",
  "",
  "MODELS AND MODES",
  "Model button in the status = model picker.",
  "Favorites from the TUI (Ctrl+F in the model picker on PC).",
  "Plan/Build - switch in the chat.",
  "",
  "FILES",
  "/ls - project file browser, tap = download",
  "Photos/PDF/text - attach to the prompt.",
  "",
  "AUTOMATION",
  "/task - schedule a task (one-off/recurring)",
  "/tasklist - list scheduled tasks",
  "",
  "OTHER",
  "/settings - bot settings",
  "/mcps - MCP servers on/off",
  "/commands and /skills - extra actions",
  "/help - full command list",
  "",
  "PC: opencode attach http://localhost:4096",
  "= the same session visible in the TUI and on your phone.",
].join("\n");

console.log(msg);
