const msg = [
  "SAMOUTCZEK BOTA",
  "",
  "SESJE I PROJEKTY",
  "/new - nowa sesja",
  "/sessions - lista sesji, tap = wznowienie",
  "/messages - historia wiadomosci (revert/fork)",
  "/rename - zmien nazwe sesji",
  "/projects - przelacz folder/projekt",
  "/open - dodaj nowy folder projektu",
  "/worktree - przelacz worktree gita",
  "/status - gdzie jestem, jaki model",
  "/abort - przerwij biezace zadanie",
  "",
  "PRACA",
  "Zwykly tekst = prompt do opencode.",
  "Kod wraca jako pliki do pobrania.",
  "Kolejka: wiadomosci pisane gdy agent pracuje czekaja na kolejke.",
  "",
  "MODELE I TRYBY",
  "Przycisk modelu w statusie = wybor modelu.",
  "Ulubione z TUI (Ctrl+F w wyborze modelu na PC).",
  "Plan/Build - przelaczanie w czacie.",
  "",
  "PLIKI",
  "/ls - przegladarka plikow projektu, tap = pobranie",
  "Zdjecia/PDF/tekst - zalacz do promptu.",
  "",
  "AUTOMATYZACJA",
  "/task - zaplanuj zadanie (jednorazowe/cykliczne)",
  "/tasklist - lista zaplanowanych",
  "",
  "INNE",
  "/settings - ustawienia bota",
  "/mcps - serwery MCP on/off",
  "/commands i /skills - dodatkowe akcje",
  "/help - pelna lista komend",
  "",
  "PC: opencode attach http://localhost:4096",
  "= ta sama sesja widoczna w TUI i na telefonie.",
].join("\n");

console.log(msg);